language: go

services:
- docker

before_install:
- docker build -t artpar/engel .

script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker build -t artpar/engel .;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push artpar/engel;
  fi
